#!/usr/bin/env python
import sys
import os
import threading
import pprint
from oauth import OAuthClient, OAuthConfig
#from user_stream import UserStream, Tweet, Friends, DictWrapper
from user_timeline import UserTimeline
from rate_limit_status import RateLimitStatus
from data_queue import GeloDataQueue
consumer_key = 'sn3SWvtYXQNqgwBkEQyNg'
consumer_secret = 'cR2GJhKzolurPYnI8pHWO7g4TlQ25UG1xpb6faPc'
request_token_url = 'https://api.twitter.com/oauth/request_token'
oauth_token_url = 'https://api.twitter.com/oauth/access_token'
oauth_authorize_url = 'https://api.twitter.com/oauth/authorize'

    
def main():
    oauth_conf = OAuthConfig('', 
                             consumer_key,
                             consumer_secret,
                             request_token_url,
                             oauth_token_url,
                             oauth_authorize_url,
                             os.path.expanduser('/var/tmp/.gelo_crawl_oauth'))
    
    client = OAuthClient(oauth_conf)
    
    client.do_oauth(client.code_input_stdin_callback)

    RateLimitStatus(client).call()
    user_timeline = UserTimeline(client)
    user_timeline.call()
    
if __name__ == '__main__':
    main()

