#!/usr/bin/env python
import sys
import json
import urllib2
import time

from data_queue import GeloDataQueue

tweet_post_url = 'http://geloge-lo.appspot.com/internal/read_tweet_from_json'

def dispatch(obj):
    json_str = json.dumps(obj.json_obj)
    try:
        print json_str
        urllib2.urlopen(tweet_post_url, json_str)
    except Exception, e:
        print e
    sys.stdout.flush()
        
    
def main():
    dq = GeloDataQueue('/var/tmp/gelo_dq')

    while True:
        for obj in dq.get_all():
            dispatch(obj)
        time.sleep(1)

if __name__ == '__main__':
    if len(sys.argv) == 2:
        tweet_post_uul = sys.argv[1]
    print 'post to: %s' % (tweet_post_url)
    sys.stdout.flush()
    main()

